id: P010544
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:14.799908
source_metadata:
  id: bdr:W3CN7814
  title: བྱང་ཆུབ་ལམ་རིམ་ཆེན་མོ་པར་གཞི་གསར་པ།
  author: ''
  volumes:
    c79f65363d1b4f43a7c8b54bb3a4102a:
      image_group_id: I3CN7816
      title: ''
      volume_number: 1
      total_pages: 986
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
