id: IEF4FAB2B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:48:20+00:00'
last_modified: '2022-06-08T14:23:04.085955+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7814
  title: བྱང་ཆུབ་ལམ་རིམ་ཆེན་མོ་པར་གཞི་གསར་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    3E9F:
      image_group_id: I3CN7816
      title: ''
      total_pages: 986
      order: 1
      base_file: 3E9F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
